//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using co.chimeralabs.ads.managed;
using co.chimeralabs.ads.managed.Models;
namespace AdClientSDKManagedTestConsole
{
	public class AnalyticsWebManagerTest
	{
		public AnalyticsWebManagerTest ()
		{
		}
		public static void Test1(){
			for (int i=0; i<950; i++) {
                TestClass obj = new TestClass("abcd", i);
                try
                {
                    AnalyticsWebManager.Push(obj, AnalyticsWebWrapperDTO.Action.AdEvent, AnalyticsWebManager.PRIORITY.LOW);
                }
                catch (TypeInitializationException e)
                {

                }
			}
		}
        public class TestClass{
            public String str1;
            public int number;
            public TestClass(String str, int num)
            {
                this.str1 = str;
                this.number = num;
            }
        }
	}
}

