//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using co.chimeralabs.ads.managed;
using co.chimeralabs.ads.managed.Models;
namespace AdClientSDKManagedTestConsole
{
	public class SystemInfoTest
	{
        public static void TestHardwareInfo(){
            Console.WriteLine("HardwareInfo.GetCPUName: " + HardwareInfo.GetCPUName());
            Console.WriteLine("HardwareInfo.GetProcessorId: " + HardwareInfo.GetProcessorId());
            Console.WriteLine("HardwareInfo.GetCPUManufacturer: " + HardwareInfo.GetCPUManufacturer());
            Console.WriteLine("HardwareInfo.GetCPUCurrentClockSpeed: " + HardwareInfo.GetCPUCurrentClockSpeed());
            Console.WriteLine("HardwareInfo.GetCPUSpeedInGHZ: " + HardwareInfo.GetCpuSpeedInGHz());
        }
	}
}

