//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace co.chimeralabs.ads.managed.Internal
{
	public interface InternalAdListener
	{
        void OnAdLoadFailed(InternalAdLoadFailedArgs args);
        void OnAdLoaded(Object context);
	}

    public class InternalAdLoadFailedArgs : EventArgs
    {
        /**
         * errorCode:-
         * 1: Network error
         * 2: Server error
         */
        private int errorCode;
        private String errorMessage;

        public InternalAdLoadFailedArgs(int errorCode, String errorMessage)
        {
            this.errorCode = errorCode;
            this.errorMessage = errorMessage;
        }
        public String getErrorMessage()
        {
            return errorMessage;
        }
        public int getErrorCode()
        {
            return errorCode;
        }
    }
}

