//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using co.chimeralabs.ads.managed.Models;
using co.chimeralabs.analytics.managed;
using co.chimeralabs.ads.managed.Utils;

namespace co.chimeralabs.ads.managed
{
	public static class AdConfigurer
	{
        private static AppParams appParams = new AppParams();
        private static IPlatform platform;
        
		public static void Startup(IPlatform pf){
            platform = pf;
            appParams.OS = platform.GetOS();
            appParams.device = platform.GetDevice();
            appParams.userId = platform.GetUserId();
            appParams.location = platform.GetLocation();
            appParams.startTime = UtilityMethods.GetCurrentTimeStamp();
            AnalyticsManager.Push(appParams, AnalyticsManager.TYPE.APP_START, AnalyticsManager.PRIORITY.HIGH);
		}

		public static void Shutdown(){
            appParams.endTime = UtilityMethods.GetCurrentTimeStamp();
            AnalyticsManager.Push(appParams, AnalyticsManager.TYPE.APP_END, AnalyticsManager.PRIORITY.HIGH);
            AnalyticsManager.FlushAllQueues();
		}

        public static IPlatform GetPlatformImpl()
        {
            return platform;
        }

        public static AppParams GetAppParams()
        {
            return appParams;
        }
	}
}