//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using co.chimeralabs.ads.managed.Models;

namespace co.chimeralabs.ads.managed
{
	public class AdInstance
	{
		private String instanceId;
		private String adId;
		private long startTime;
		private long lastTime;
		private Boolean isInstancedDisplayed = false;
		public AdInstance (String instanceId, String adId)
		{
			this.instanceId = instanceId;
            this.adId = adId;
			startTime = DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond;
			lastTime = 0;
            AnalyticsWebManager.Push(new InstanceEventDTO(this.adId, this.instanceId, InstanceEventDTO.EventType.AdAttachedToInstance, ""), AnalyticsWebWrapperDTO.Action.InstanceEvent, AnalyticsWebManager.PRIORITY.HIGH);
		}
		public String GetInstanceId(){
			return this.instanceId;
		}
		public String GetAdId(){
			return this.adId;
		}
		public void UpdateVisibilityMetric(float cameraLookAtX, float cameraLookAtY, float cameraLookAtZ, float cameraX, float cameraY, float cameraZ, float adObjectX, float adObjectY, float adObjectZ){
			long newTime = DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond - startTime;
			if ((newTime - lastTime) > AnalyticsWebManager.timeResolution) {
				lastTime = newTime;
                InstanceVisibilityMetricDTO dtoObj = new InstanceVisibilityMetricDTO(this.adId, this.instanceId, newTime, cameraLookAtX, cameraLookAtY, cameraLookAtZ, cameraX, cameraY, cameraZ, adObjectX, adObjectY, adObjectZ);
                AnalyticsWebManager.Push(dtoObj, AnalyticsWebWrapperDTO.Action.AdInstanceVisibilityMetricUpdate, AnalyticsWebManager.PRIORITY.LOW);
			}
		}
		public void MarkInstanceDisplayedTrue(){
			isInstancedDisplayed = true;
			AnalyticsWebManager.Push(new InstanceEventDTO(this.adId, this.instanceId, InstanceEventDTO.EventType.InstanceDisplayed, ""), AnalyticsWebWrapperDTO.Action.InstanceEvent, AnalyticsWebManager.PRIORITY.HIGH);
		}
		public Boolean IsInstanceDisplayed(){
			return this.isInstancedDisplayed;
		}
	}
}