//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace co.chimeralabs.ads.managed
{
	public interface AdUnitListener
	{
        void OnAdUnitLoadFailed(AdUnitFailedArgs args);
        void OnAdUnitLoaded(Object context);
	}

    public class AdUnitFailedArgs : EventArgs
    {
        public String errorMessage { get; set; }
        public ErrorCode errorCode { get; set; }
        public String adUnitId { get; set; }

        public AdUnitFailedArgs(ErrorCode errorCode, String errorMessage, String adUnitId)
        {
            this.errorCode = errorCode;
            this.errorMessage = errorMessage;
            this.adUnitId = adUnitId;
        }
        public enum ErrorCode
        {
            NO_AD_LOADED,
            FEW_ADS_LOADED
        }
    }
}
