//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Net;
using Newtonsoft.Json;
using co.chimeralabs.ads.managed.Models;

namespace co.chimeralabs.ads.managed
{
	public class AnalyticsWebManager
	{
        private static Uri uri = new Uri("http://localhost:8080/adserver/analytics");
		public static long timeResolution = 500; //milliseconds
        private static Queue highPriorityQueue = new Queue();
        private static Queue lowPriorityQueue = new Queue();
        private static int highPriorityQueueTrigger = 5;
        private static int lowPriorityQueueTrigger = 100;
		private static Object[] lowPriorityQueuePushed;
		private static Object[] highPriorityQueuePushed;

		public AnalyticsWebManager ()
		{
		}

		public static void FlushAllQueues(){
			if (highPriorityQueue.Count > 0)
				FlushHighPriorityQueue ();
			if (lowPriorityQueue.Count > 0)
				FlushLowPriorityQueue ();
		}
		private static void FlushHighPriorityQueue(){
			highPriorityQueuePushed = highPriorityQueue.ToArray();
			highPriorityQueue.Clear();
            WebClient webClient = new WebClient();
            webClient.Headers.Add("Content-Type", "application/json");
            webClient.UploadStringCompleted += new UploadStringCompletedEventHandler(OnHighPriorityUploadFinished);
			String uploadString = JsonConvert.SerializeObject(highPriorityQueuePushed);
			try
			{
				webClient.UploadStringAsync(uri, uploadString);
			}
			catch(System.Net.WebException e){
				Console.WriteLine("Exception caught: {0}", e);
			}
			catch (ArgumentNullException e)
			{
				Console.WriteLine("Exception caught: {0}", e);
			}
		}
		private static void FlushLowPriorityQueue(){
			lowPriorityQueuePushed = lowPriorityQueue.ToArray();
			lowPriorityQueue.Clear();
			WebClient webClient = new WebClient();
            webClient.Headers.Add("Content-Type", "application/json");
			webClient.UploadStringCompleted += new UploadStringCompletedEventHandler(OnLowPriorityUploadFinished);
			String uploadString = JsonConvert.SerializeObject(lowPriorityQueuePushed);
			try
			{
				webClient.UploadStringAsync(uri, uploadString);
			}
			catch(System.Net.WebException e){
				Console.WriteLine("Exception caught: {0}", e);
			}
			catch (ArgumentNullException e)
			{
				Console.WriteLine("Exception caught: {0}", e);
			}
		}
        public static void Push(Object obj, AnalyticsWebWrapperDTO.Action action, PRIORITY priority)
        {
            String objSerlialized = JsonConvert.SerializeObject(obj);
            AnalyticsWebWrapperDTO dto = new AnalyticsWebWrapperDTO(action, objSerlialized);
            switch (priority)
            {
            case PRIORITY.HIGH:
                highPriorityQueue.Enqueue(dto);
                if(highPriorityQueue.Count >= highPriorityQueueTrigger){
					FlushHighPriorityQueue();
				}
                break;
            case PRIORITY.LOW:
                lowPriorityQueue.Enqueue(dto);
				if(lowPriorityQueue.Count >= lowPriorityQueueTrigger){
					FlushLowPriorityQueue();
				}
                break;
            }
        }
        
		private static void OnHighPriorityUploadFinished(System.Object sender, UploadStringCompletedEventArgs args){
		}

		private static void OnLowPriorityUploadFinished(System.Object sender, UploadStringCompletedEventArgs args){
		}
        public enum PRIORITY
        {
            HIGH, LOW
        }
	}
}

