//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using co.chimeralabs.ads.managed.Models;

namespace co.chimeralabs.ads.managed
{
	public class ImageTextureAdInstance:AdInstance
	{
        private ImageTextureAd ad;
        public ImageTextureAdInstance(String instanceId, ImageTextureAd ad, IAdObject adObject):base(instanceId, ad.adUnitId, ad.adServingId, adObject){
            this.ad = ad;
        }
        public ITexture GetDiffuseTexture()
        {
            return ad.GetDiffuseTexture();
        }
	}
}
