//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using co.chimeralabs.ads.managed.Models;
using co.chimeralabs.ads.managed.Internal;

namespace co.chimeralabs.ads.managed
{
    public class ImageTextureAd : InternalAdListener
    {
        private TextureData diffuseTexture;
        public String adServingId { get; set; }
        public String adUnitId { get; set; }
        public String diffuseTextureUrl { get; set; }
        public InternalAdListener parentListener;

        public ImageTextureAd(String adServingId, String adUnitId, String diffuseTextureUrl, InternalAdListener parentListener)
        {
            this.adServingId = adServingId;
            this.adUnitId = adUnitId;
            this.diffuseTextureUrl = diffuseTextureUrl;
            this.parentListener = parentListener;
        }
        public void DownloadAd()
        {
            diffuseTexture = new TextureData(diffuseTextureUrl, this);
            diffuseTexture.DownloadTextureData();
        }
        public void OnAdLoadFailed(InternalAdLoadFailedArgs args)
        {
            parentListener.OnAdLoadFailed(args);
        }
        public void OnAdLoaded(Object context)
        {
            diffuseTexture = (TextureData)context;
            parentListener.OnAdLoaded(this);
        }
        public ITexture GetDiffuseTexture()
        {
            return diffuseTexture.GetTexture();
        }
    }
}
