//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace co.chimeralabs.ads.managed.Models
{
	public class AdRequest
	{
		public AdType adType{get; set;}
        public String adUnitId { get; set; }
        public int nDistinctAds { get; set; }
        public AdRequest()
        {

        }

        public AdRequest(AdType adType, String adUnitId, int nDistinctAds)
        {
            this.adType = adType;
            this.adUnitId = adUnitId;
            this.nDistinctAds = nDistinctAds;
        }

	}
}

