//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace co.chimeralabs.ads.managed.Models
{
	public class AdResponse
	{
        public List<AdResourceMetadata> adResources { set; get; }
        public String adUnitId { set; get; }
        public int errorCode { set; get; }
        public String errorMsg { set; get; }
	}
}