//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace co.chimeralabs.ads.managed.Models
{
	public class AdRequest
	{
		private AdType adType;
		public AdType getAdType(){
			return this.adType;
		}
		public void setAdType(AdType adType){
			this.adType = adType;
		}
	}
}

