//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace co.chimeralabs.ads.managed.Models
{
	public class AppParams
	{
        public String location { set; get; }
        public String hmd { set; get; }
        public String OS { set; get; }
        public String device { set; get; }//mobile or pc or tablet etc
        public String userId { set; get; }
        public long startTime { set; get; }
        public long endTime { set; get; }
        public AppParams()
        {

        }

	}
}

